### PR TITLE
run the mcb hook in parallel, instead of running one by one

### PR DESCRIPTION
**Pull request by asxalex**
from my point of view, the subscription handler should be run in parallel, like an http server, every time the 'api'(a publication in nats) is called, the handler should be called, instead of waiting for the last one to finish. Making the running of "mcb" as a golang coroutine satisfies this need. please make me informed if the change spoils something or it would cause some disaster :)

### CODE REVIEW

**Comment by asxalex** [comment]
oh, this makes some test failed~

**Comment by asxalex** [comment]
As i'd like to get the outcome of the mcb, and reply some message to the publisher. If i make my handler a go routine, whether communicating with chan or not, I still have to wait for the handler to finish.

**Comment by kozlovic** [comment]
@asxalex As @ripienaar mentioned, you should have your message callback do something like: 
```
func (m *nats.Msg) {
  go handleMsg(m)
}
```
As you have seen from the tests and some (lots ?) users rely on the ordering of invocation of the message callback for a given subscription.

Therefore, we are closing this PR since there is a very easy way and non disruptive way to the community to implement your desired behavior.

Thank you for using NATS!

**Comment by asxalex** [comment]
@kozlovic Ah, I confused myself, sorry for that. That solved my problem, thanks a lot :)

**Pull request closed without merging**
