### PR TITLE
Add gosimple linting

### PR DESCRIPTION
**Pull request by y0ssar1an**
`gosimple` is a linter from the author of `staticcheck`. It catches [a number of code smell issues](https://github.com/dominikh/go-simple#checks).

### CODE REVIEW

**Comment by kozlovic** [comment]
Have you run it locally and got the only error you fixed? On Travis run, it looks like there is a similar issue:
```
/home/travis/gopath/src/github.com/nats-io/nats/encoders/protobuf/protobuf_enc.go:62:2: 'if err != nil { return err }; return nil' can be simplified to 'return err'
```

**Comment by y0ssar1an** [comment]
Yep. Same issue as before. Local `gosimple ./...` reported no issues. I may have a configuration issue with my system ¯\_(ツ)_/¯

Anyway, it looks like it's clean now.

**Comment by kozlovic** [comment]
LGTM

**Comment by y0ssar1an** [comment]
The `gosimple` import path has changed to this:
```
go get -u honnef.co/go/tools/cmd/gosimple
```
[Details here](https://www.reddit.com/r/golang/comments/5pzsmu/dominikh_static_analysis_tools_staticcheck/?st=iycfcrrk&sh=4928b9c1)

**Comment by kozlovic** [comment]
@y0ssar1an Once #255 is fixed and merged, would you mind rebasing and update with new url (and also move it higher in the list of things to run, like I asked for `staticcheck` in the other PR)? Again, I could do that too if you prefer, just let me know.

**Comment by kozlovic** [comment]
@y0ssar1an Since I had other things to change, I decided to submit a PR to cover this and the other that you have submitted. Hope its ok. The new PR is https://github.com/nats-io/go-nats/pull/257.
Thanks again!

**Pull request closed without merging**
