### PR TITLE
Option for background connection attempts

### PR DESCRIPTION
**Pull request by shaxbee**
Provides `Background(ctx context.Context)` option for asynchronous connection process, making `Options.Connect()` non-blocking and always return nil error.

### CODE REVIEW

**Comment by wallyqs** [comment]
Thanks for the PR, I don't think that we should add a `Background` context state to the client right now for the connection attempts, I would expect a background state to mean for example that the client will be connected for as long as the context is valid and disconnect from NATS when the context is canceled.

Also we don't currently support reconnection attempts for when establishing the connection on the first attempt (see: https://github.com/nats-io/go-nats/issues/195)

On the other hand, good news is that you could still implement your own custom logic using a custom dialer, and also make use of APIs like `DialContext` part of the standard library which support connection tracing, sharing a couple of examples below:

```go
type customDialer struct {
	ctx context.Context
}

func (cd *customDialer) Dial(network, address string) (net.Conn, error) {
	d := &net.Dialer{}

	for lastAttempt := time.Now(); ; lastAttempt = time.Now() {
		select {
		case <-cd.ctx.Done():
			return nil, cd.ctx.Err()
		default:
			if conn, err := d.DialContext(cd.ctx, network, address); err == nil {
				return conn, nil
			}
		}

		sleepTime := time.Duration(0)
		if time.Since(lastAttempt) < 2*time.Second {
			sleepTime = 2*time.Second - time.Since(lastAttempt)
		}
		if sleepTime <= 0 {
			runtime.Gosched()
		} else {
			time.Sleep(sleepTime)
		}
	}
}

func main() {
	ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(5*time.Second))
	defer cancel()

	cd := &customDialer{
		ctx: ctx,
	}
	var err error
	var nc *nats.Conn
	opts := []nats.Option{nats.SetCustomDialer(cd), nats.ReconnectWait(2 * time.Second)}
	go func() {
		nc, err = nats.Connect("127.0.0.1:4222", opts...)
	}()
	// ...
```

Or enabling trace borrowing `httptrace` package hooks:

```go
	trace := &httptrace.ClientTrace{
		ConnectStart: func(network, addr string) {
			log.Println("Connection attempt...")
		},
		ConnectDone: func(network, addr string, err error) {
			if err == nil {
				log.Println("Established TCP connection!")
				cancel()
			}
		},
	}
	ctx = httptrace.WithClientTrace(ctx, trace)
	cd := &customDialer{
		ctx: ctx,
	}

	var err error
	var nc *nats.Conn
	opts := []nats.Option{nats.SetCustomDialer(cd), nats.ReconnectWait(2 * time.Second)}
```

**Comment by shaxbee** [comment]
Thanks a lot! Custom dialer solution looks much cleaner!

**Comment by wallyqs** [comment]
no problem :) ok closing this one for now

**Comment by wallyqs** [comment]
Added full example on a gist here: https://gist.github.com/wallyqs/2cf37ed3b19517e16e466461376fd53b

**Comment by shaxbee** [comment]
@wallyqs The one problem i see is that it is not possible to connect in non-blocking way, is there any way to achieve this?

**Comment by ripienaar** [comment]
@shaxbee I am curious what the use case is for non blocking backgrounded connect? If you want to do message processing in the background just start the worker code in a go routine?

**Comment by shaxbee** [comment]
@ripienaar This is same as #195 - in cloud system i'd like service to start even if nats is unavailable momentarily for example due to restart or any other issue, similarly to what happens in database/sql - calling sql.Open() doesn't block even if destination host is unreachable.

**Comment by ripienaar** [comment]
You can still start - just handle your routine that connects and process data in a go routine?

```
go thing.Run(ctx, wg)

// continue startup

wg.Wait()
```

this way your main loop that might potentially block on the network initial connection doesnt hold up the startup loop.  It's a very common pattern in Go and I think NATS not reinventing this wheel is just fine.

**Pull request closed without merging**
