### PR TITLE
Add output to example_test.go

### PR DESCRIPTION
**Pull request by wallyqs**
Noticed that we are missing the `Output` comments section in the examples from `example_test`, so this PR includes them in order to run these examples as part of the build.

### CODE REVIEW

**Comment by kozlovic** [comment]
No big deal, but there are 2 examples that use 1 second for the NextMsg() timeout knowing that the call is going to timeout. It's 2 seconds more for the test suite to pass, again no big deal, but do you think we could reduce this to a low value? We could put a comment saying that we use a small timeout on purpose since we know we are not going to get any message anyway.

**Comment by kozlovic** [comment]
LGTM

**Comment by wallyqs** [comment]
thanks @kozlovic ok updated to shorten the timeouts in those.

**Comment by kozlovic** [comment]
@wallyqs Saw that, thanks, and LGTM.

**Comment by wallyqs** [comment]
Closing this one for now, might revisit after fixing conflicts.

**Pull request closed without merging**
